### ISSUE TITLE
Headless Example Requires Interaction

### ISSUE THREAD

**Issue by spottedmahn** [Microsoft/vsts-auth-samples#13]
I've briefly explored the [device profile sample](https://github.com/Microsoft/vsts-auth-samples/tree/master/DeviceProfileSample) and I see it requires user interaction.  How does this app support the headless scenario then if it requires user interaction?

Maybe I'm misunderstanding headless; to me, headless means no UI and I can run the exe/job w/o any user interaction.  Maybe I have the wrong interpretation of headless?

**Comment by justmarks** [comment]
I hear you @spottedmahn and I would categorize it as "somewhat-headless" :)  The scenario here is if you have a machine without an interactive UI, you can get ANOTHER machine to prompt you for passing credentials.  That's what the device profile flow provides.  For a fully non-interactive flow, you can pass username/password into the AcquireTokenAsync call

```
// Uses a username and password to fetch an ADAL token.
var userNamePasswordAssertion = new UserPasswordCredential(userName, password);
var context = new AuthenticationContext("https://login.microsoftonline.com/common");
var result = context.AcquireTokenAsync(VstsResourceId, ClientId, userNamePasswordAssertion).Result;
```
